version: '3.9'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080